-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.17-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.2.0.6228
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for db_ams
DROP DATABASE IF EXISTS `db_ams`;
CREATE DATABASE IF NOT EXISTS `db_ams` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `db_ams`;

-- Dumping structure for table db_ams.dokumen
DROP TABLE IF EXISTS `dokumen`;
CREATE TABLE IF NOT EXISTS `dokumen` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_dokumen` varchar(50) NOT NULL,
  `bidang` varchar(50) DEFAULT NULL,
  `jenis_dokumen` varchar(50) DEFAULT NULL,
  `judul_dokumen` varchar(100) DEFAULT NULL,
  `tgl_upload` date DEFAULT NULL,
  `author` varchar(50) DEFAULT NULL,
  `file_documen` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`nomor_dokumen`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_ams.dokumen: ~42 rows (approximately)
DELETE FROM `dokumen`;
/*!40000 ALTER TABLE `dokumen` DISABLE KEYS */;
INSERT INTO `dokumen` (`id`, `nomor_dokumen`, `bidang`, `jenis_dokumen`, `judul_dokumen`, `tgl_upload`, `author`, `file_documen`) VALUES
	(44, '002/SPO/LOG UM/RS PMC/I-21', 'PENUNJANG OPERASIONAL', 'SPO', 'SPO PENDISTRIBUSIAN BARANG', '2021-03-03', 'Siti Robiah', 'SPO_PENDISTRIBUSIAN_BARANG.pdf'),
	(45, '003/SPO/LOG UM/RS PMC/I-21', 'PENUNJANG OPERASIONAL', 'SPO', 'SPO PENGAMBILAN BARANG', '2021-03-03', 'Siti Robiah', 'SPO_PENGAMBILAN_BARANG.pdf'),
	(7, '005/SPO/LOGUM/RS.PMC/I-21', 'PENUNJANG OPERASIONAL', 'SPO', 'SPO DATABASE BARANG', '2021-03-03', 'Siti Robiah', 'SPO_DATABASE_BARANG.pdf'),
	(22, '006/SPO/KESLING/RS.PMC/I-20', 'PENUNJANG OPERASIONAL', 'SPO', 'SPO PEMBERIAN CLORIN DI IPAL', '2021-03-03', 'Siti Robiah', 'SPO_PEMBERIAN_CLORIN_DI_IPAL.pdf'),
	(3, '006/SPO/YANMED/RSPMC/1-2021', 'YANMED', 'SPO', 'SPO ASSESMEN PASIEN SEBELUM DILAKUKAN VAKSIN COVID', '2021-03-03', 'Siti Robiah', 'SPO_ASSESMEN_PASIEN_SEBELUM_DILAKUKAN_VAKSIN_COVID'),
	(6, '007/SPO/KESLING/RSPMC/I-21', 'PENUNJANG OPERASIONAL', 'SPO', 'SPO CARA PEMBERIAN NUTRISI IPAL', '2021-03-03', 'Siti Robiah', 'SPO_CARA_PEMBERIAN_NUTRISI_IPAL.pdf'),
	(37, '007/SPO/POLI/RS/PMC/1-2021', 'YANMED', 'SPO', 'SPO PENANGANAN REAKSI ANAFILATIK SETELAH VAKSIN', '2021-03-03', 'Siti Robiah', 'SPO_PENANGANAN_REAKSI_ANAFILATIK_SETELAH_VAKSIN.pd'),
	(31, '008/SPO/KESLING/RS.PMC/I-21', 'PENUNJANG OPERASIONAL', 'SPO', 'SPO PEMELIHARAAN AIR LIMBAH', '2021-03-03', 'Siti Robiah', 'SPO_PEMELIHARAAN_AIR_LIMBAH.pdf'),
	(43, '009/SPO/LAUNDRY/RS PMC/I-21', 'PENUNJANG OPERASIONAL', 'SPO', 'SPO PENCUCIAN GORDEN', '2021-03-03', 'Siti Robiah', 'SPO_PENCUCIAN_GORDEN.pdf'),
	(47, '009/SPO/YANMED/RS PMC/I-2021', 'YANMED', 'SPO', 'SPO PENGELOLAAN VAKSIN PADA SAAT PELAYANAN', '2021-03-03', 'Siti Robiah', 'SPO_PENGELOLAAN_VAKSIN_PADA_SAAT_PELAYANAN.pdf'),
	(16, '01/SPO/KEU/RS.PMC/I-21', 'KEUANGAN', 'SPO', 'SPO ORIENTASI KARYAWAN KASIR RS PMC', '2021-03-03', 'Siti Robiah', 'SPO_ORIENTASI_KARYAWAN_KASIR_RS_PMC.pdf'),
	(46, '010/SPO/KESLING/RS PMC/I-21', 'PENUNJANG OPERASIONAL', 'SPO', 'SPO PENGELOLAAN LIMBAH', '2021-03-03', 'Siti Robiah', 'SPO_PENGELOLAAN_LIMBAH.pdf'),
	(17, '236/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO ORIENTASI PASIEN BARU RAWAT INAP', '2021-03-03', 'Siti Robiah', 'SPO_ORIENTASI_PASIEN_BARU_RAWAT_INAP.pdf'),
	(34, '237/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMERIKSAAN GLASGLOW\'S COMA SCALE (GCS)', '2021-03-03', 'Siti Robiah', 'SPO_PEMERIKSAAN_GLASGLOWS_COMA_SCALE_(GCS).pdf'),
	(21, '238/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMASANGAN OKSIGEN', '2021-03-03', 'Siti Robiah', 'SPO_PEMASANGAN_OKSIGEN.pdf'),
	(24, '240/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMBERIAN OBAT INTRAVENA LANGSUNG', '2021-03-03', 'Siti Robiah', 'SPO_PEMBERIAN_OBAT_INTRAVENA_LANGSUNG.pdf'),
	(25, '241/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMBERIAN OBAT INTRAVENA TDK LANGSUNG', '2021-03-03', 'Siti Robiah', 'SPO_PEMBERIAN_OBAT_INTRAVENA_TDK_LANGSUNG.pdf'),
	(33, '242/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMERIKSAAN EKG', '2021-03-03', 'Siti Robiah', 'SPO_PEMERIKSAAN_EKG.pdf'),
	(36, '243/SPO/POLI/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMERIKSAAN VISUS', '2021-03-03', 'Siti Robiah', 'SPO_PEMERIKSAAN_VISUS.pdf'),
	(32, '244/SPO/POLI/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMERIKSAAN BUTA WARNA', '2021-03-03', 'Siti Robiah', 'SPO_PEMERIKSAAN_BUTA_WARNA.pdf'),
	(42, '245/SPO/POLI/RS PMC/XI-20', 'YANMED', 'SPO', 'SPO PENATALAKSANAAN TREDMIL', '2021-03-03', 'Siti Robiah', 'SPO_PENATALAKSANAAN_TREDMIL.pdf'),
	(15, '246/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO MENYIAPKAN TEMPAT TIDUR PASIEN', '2021-03-03', 'Siti Robiah', 'SPO_MENYIAPKAN_TEMPAT_TIDUR_PASIEN.pdf'),
	(10, '248/SPO/VK/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO KEHAMILAN KEMBAR (GAMELI)', '2021-03-03', 'Siti Robiah', 'SPO_KEHAMILAN_KEMBAR_(GAMELI).pdf'),
	(1, '251/SPO/VK/RSPMC/XI-20', 'YANMED', 'SPO', 'SPO ASISTEN DALAM MENOLONG PARTUS', '2021-03-03', 'Siti Robiah', 'SPO_ASISTEN_DALAM_MENOLONG_PARTUS.pdf'),
	(2, '252/SPO/VK/RSPMC/XI-20', 'YANMED', 'SPO', 'SPO ASISTEN DOKTER SPESIALIS KANDUNGAN UNTUK TINDAKAN KURETASE', '2021-03-03', 'Siti Robiah', 'SPO_ASISTEN_DOKTER_SPESIALIS_KANDUNGAN_UNTUK_TINDA'),
	(5, '253/SPO/VK/RSPMC/XI-20', 'YANMED', 'SPO', 'SPO CARA MENGELUARKAN ASI PADA IBU NIFAS', '2021-03-03', 'Siti Robiah', 'SPO_CARA_MENGELUARKAN_ASI_PADA_IBU_NIFAS.pdf'),
	(8, '254/SPO/VK/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO HIPERTENSI DALAM KEHAMILAN', '2021-03-03', 'Siti Robiah', 'SPO_HIPERTENSI_DALAM_KEHAMILAN.pdf'),
	(9, '255/SPO/VK/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO IBU HAMIL DENGAN PENYAKIT JANTUNG', '2021-03-03', 'Siti Robiah', 'SPO_IBU_HAMIL_DENGAN_PENYAKIT_JANTUNG.pdf'),
	(11, '257/SPO/VK/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO LETAK LINTANG', '2021-03-03', 'Siti Robiah', 'SPO_LETAK_LINTANG.pdf'),
	(18, '258/SPO/VK/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PANANGGULANGAN PERSALINAN DENGAN KETUBAN HIJAU KENTAL', '2021-03-03', 'Siti Robiah', 'SPO_PANANGGULANGAN_PERSALINAN_DENGAN_KETUBAN_HIJAU'),
	(39, '259/SPO/VK/RS PMC/XI-20', 'YANMED', 'SPO', 'SPO PENANGGULANGAN PLASENTA PREVIA', '2021-03-03', 'Siti Robiah', 'SPO_PENANGGULANGAN_PLASENTA_PREVIA.pdf'),
	(40, '260/SPO/VK/RS PMC/XI-20', 'YANMED', 'SPO', 'SPO PENANGGULANGAN RUPTURE UTERI', '2021-03-03', 'Siti Robiah', 'SPO_PENANGGULANGAN_RUPTURE_UTERI.pdf'),
	(41, '261/SPO/VK/RS PMC/XI-20', 'YANMED', 'SPO', 'SPO PENANGGULANGAN SOLUTIO PLASENTA', '2021-03-03', 'Siti Robiah', 'SPO_PENANGGULANGAN_SOLUTIO_PLASENTA.pdf'),
	(38, '262/SPO/VK/RS PMC/XI-20', 'YANMED', 'SPO', 'SPO PENANGGULANGAN PENDARAHAN PADA KEHAMILAN MUDA (ABORTUS)', '2021-03-03', 'Siti Robiah', 'SPO_PENANGGULANGAN_PENDARAHAN_PADA_KEHAMILAN_MUDA_'),
	(4, '269/SPO/VK/RSPMC/XI-20', 'YANMED', 'SPO', 'SPO ASUHAN PERSALINAN NORMAL', '2021-03-03', 'Siti Robiah', 'SPO_ASUHAN_PERSALINAN_NORMAL.pdf'),
	(14, '273/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO MENGUKUR TEKANAN DARAH', '2021-03-03', 'Siti Robiah', 'SPO_MENGUKUR_TEKANAN_DARAH.pdf'),
	(13, '274/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO MENGHITUNG PERNAPASAN', '2021-03-03', 'Siti Robiah', 'SPO_MENGHITUNG_PERNAPASAN.pdf'),
	(35, '275/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMERIKSAAN SUHU AXILA', '2021-03-03', 'Siti Robiah', 'SPO_PEMERIKSAAN_SUHU_AXILA.pdf'),
	(23, '276/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMBERIAN OBAT INTRA MUSKULER', '2021-03-03', 'Siti Robiah', 'SPO_PEMBERIAN_OBAT_INTRA_MUSKULER.pdf'),
	(28, '277/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMBERIAN OBAT SUBCUTAN', '2021-03-03', 'Siti Robiah', 'SPO_PEMBERIAN_OBAT_SUBCUTAN.pdf'),
	(29, '278/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMBERIAN OBAT SUPOSITORIAL', '2021-03-03', 'Siti Robiah', 'SPO_PEMBERIAN_OBAT_SUPOSITORIAL.pdf'),
	(27, '279/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMBERIAN OBAT SALEP KULIT', '2021-03-03', 'Siti Robiah', 'SPO_PEMBERIAN_OBAT_SALEP_KULIT.pdf'),
	(12, '280/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO MEMBERIKAN OBAT ORAL', '2021-03-03', 'Siti Robiah', 'SPO_MEMBERIKAN_OBAT_ORAL.pdf'),
	(30, '281/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMBERIAN OBAT TETES MATA', '2021-03-03', 'Siti Robiah', 'SPO_PEMBERIAN_OBAT_TETES_MATA.pdf'),
	(26, '282/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMBERIAN OBAT MELALUI TELINGA', '2021-03-03', 'Siti Robiah', 'SPO_PEMBERIAN_OBAT_MELALUI_TELINGA.pdf'),
	(20, '284/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PEMASANGAN INFUS', '2021-03-03', 'Siti Robiah', 'SPO_PEMASANGAN_INFUS.pdf'),
	(19, '285/SPO/YANMED/RS.PMC/XI-20', 'YANMED', 'SPO', 'SPO PELEPASAN INFUS', '2021-03-03', 'Siti Robiah', 'SPO_PELEPASAN_INFUS.pdf');
/*!40000 ALTER TABLE `dokumen` ENABLE KEYS */;

-- Dumping structure for table db_ams.edaran
DROP TABLE IF EXISTS `edaran`;
CREATE TABLE IF NOT EXISTS `edaran` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_surat` varchar(50) NOT NULL,
  `isi_surat` varchar(50) DEFAULT NULL,
  `publish` varchar(50) DEFAULT NULL,
  `tgl_publish` date DEFAULT NULL,
  `file_surat` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`nomor_surat`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_ams.edaran: ~0 rows (approximately)
DELETE FROM `edaran`;
/*!40000 ALTER TABLE `edaran` DISABLE KEYS */;
/*!40000 ALTER TABLE `edaran` ENABLE KEYS */;

-- Dumping structure for table db_ams.memo
DROP TABLE IF EXISTS `memo`;
CREATE TABLE IF NOT EXISTS `memo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nomor_memo` varchar(50) NOT NULL,
  `ket` varchar(50) DEFAULT NULL,
  `publish` varchar(50) DEFAULT NULL,
  `tgl_publish` date DEFAULT NULL,
  `file_memo` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`nomor_memo`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_ams.memo: ~0 rows (approximately)
DELETE FROM `memo`;
/*!40000 ALTER TABLE `memo` DISABLE KEYS */;
/*!40000 ALTER TABLE `memo` ENABLE KEYS */;

-- Dumping structure for table db_ams.tb_bidang
DROP TABLE IF EXISTS `tb_bidang`;
CREATE TABLE IF NOT EXISTS `tb_bidang` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bidang` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_ams.tb_bidang: ~4 rows (approximately)
DELETE FROM `tb_bidang`;
/*!40000 ALTER TABLE `tb_bidang` DISABLE KEYS */;
INSERT INTO `tb_bidang` (`id`, `bidang`) VALUES
	(1, 'YANMED'),
	(2, 'KEUANGAN'),
	(3, 'PENUNJANG OPERASIONAL'),
	(4, 'KESEKRETARIATAN');
/*!40000 ALTER TABLE `tb_bidang` ENABLE KEYS */;

-- Dumping structure for table db_ams.tb_jenis_surat
DROP TABLE IF EXISTS `tb_jenis_surat`;
CREATE TABLE IF NOT EXISTS `tb_jenis_surat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `jenis_surat` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_ams.tb_jenis_surat: ~4 rows (approximately)
DELETE FROM `tb_jenis_surat`;
/*!40000 ALTER TABLE `tb_jenis_surat` DISABLE KEYS */;
INSERT INTO `tb_jenis_surat` (`id`, `jenis_surat`) VALUES
	(1, 'SPO'),
	(2, 'PEDOMAN'),
	(3, 'PANDUAN'),
	(4, 'PROGRAM KERJA');
/*!40000 ALTER TABLE `tb_jenis_surat` ENABLE KEYS */;

-- Dumping structure for table db_ams.user
DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama` varchar(50) DEFAULT NULL,
  `unit` varchar(50) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `password` varchar(50) DEFAULT NULL,
  `level` enum('Super Admin','Admin','User') DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4;

-- Dumping data for table db_ams.user: ~4 rows (approximately)
DELETE FROM `user`;
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
INSERT INTO `user` (`id`, `nama`, `unit`, `username`, `password`, `level`) VALUES
	(1, 'Super Admin', 'IT', 'super', '21232f297a57a5a743894a0e4a801fc3', 'Super Admin'),
	(2, 'Admin', 'IT', 'admin', '21232f297a57a5a743894a0e4a801fc3', 'Admin'),
	(6, 'Siti Robiah', 'SEKRETARIAT', 'siti', '181c9bbf1d1fc37c9ff66dc859c841f1', 'Super Admin'),
	(7, 'Eki Prisma', 'FRONT OFFICE', 'eki', 'dea12ffb2578f2789b8bde3d446f3415', 'User'),
	(8, 'Fitria Eki', 'REKAM MEDIS', 'fitria', 'daed6ec547a88a5780ace966202b206e', 'User');
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
